cordex_esd_manager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from experiments import views as experiment_views
from submissions import views as submission_views


router = routers.DefaultRouter()
router.register(r'timeperiods', experiment_views.TimePeriodViewSet)
router.register(r'datasets', experiment_views.DatasetViewSet)
router.register(r'meta-experiments', experiment_views.MetaExperimentViewSet)
router.register(r'experiments', experiment_views.ExperimentViewSet)

router.register(r'models', submission_views.ModelViewSet)
router.register(r'modelmeta', submission_views.ModelMetaViewSet)
router.register(r'submissions', submission_views.SubmissionViewSet)
router.register(r'uploads', submission_views.UploadView)



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cordex_esd_manager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'web.views.index', name='index'),
    url(r'^projects/([-\w]+)/$', 'web.views.experiments', name='web-experiments'),
    url(r'^projects/([-\w]+)/([-\w]+)/([-\w]+)$', 'web.views.experiment_detail', name='web-experiment-detail'), 
    
    url(r'^submissions-admin/$', 'web.views.admin_submissions', name='web-admin-submissions'),
    url(r'^submissions/$', 'web.views.user_submissions', name='web-user-submissions'),
    url(r'^submissions/([-\w]+)/([-\w]+)/([-\w]+)$', 'web.views.experiment_submissions', name='web-experiment-submissions'),
    
    url(r'^models/$', 'web.views.models_list', name='web-models-list'),
    url(r'^models/([-\w]+)/$', 'web.views.model_edit', name='web-model-edit'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/login', 'web.views.login_view', name='web-login'),
    url(r'^accounts/profile', 'web.views.user_profile', name='web-profile'),
    url(r'^accounts/logout', 'web.views.logout_view', name='web-logout'),

)

experiments/models.py
from django.db import models
from profiles.models import Profile

import datetime


DATASET_CATEGORIES = (('observed', 'Observed datasets'), ('re-analysis', 'Re-analysis datasets'), ('CMIP5', 'CMIP5 Models'))
EXPERIMENT_DATASET_CATEGORIES = (('predictor', 'Predictor'), ('predictand', 'Predictand'))
EXPERIMENT_VARIABLE_CATEGORIES = (('forcing', 'Forcing'), ('output', 'Output'))
TIMEPERIOD_CATEGORIES = (('calibration', 'Calibration period'), ('validation', 'Validation period'))
FREQUENCIES = (('day', 'daily data'), ('month', 'monthly data'))
META_DEPENDENCY_CATEGORIES = (('Equal', 'equal'),)
META_TARGETS = (('model', 'Model'), ('submission', 'Submission'))


class TimePeriod(models.Model):

	short_name = models.CharField(max_length=50, default="", blank=True)
	begin = models.DateTimeField(default=datetime.datetime(1900,1,1))
	end = models.DateTimeField(default=datetime.datetime(1999,12,31))

	#exclude = models.ManyToManyField('TimePeriod')

	def __unicode__(self):
		return "{} - {}".format(self.begin, self.end)


class Variable(models.Model):

	short_name = models.SlugField(max_length=50, default="", blank=False, unique=True)
	long_name = models.CharField(max_length=100, default="", blank=True)
	standard_name = models.CharField(max_length=100, default="", blank=True)
	units = models.CharField(max_length=15)

	comments = models.TextField(blank=True, default="")

	def __unicode__(self):
		return self.standard_name


class Project(models.Model):

	slug = models.SlugField(max_length=50)
	title = models.CharField(max_length=50, default='')
	description = models.TextField()
	url = models.URLField(default="")

	created_by = models.ForeignKey(Profile, null=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.title

class Dataset(models.Model):

	slug = models.SlugField(max_length=50)
	title = models.CharField(max_length=50, default='')
	description = models.TextField()
	category = models.CharField(max_length=20, choices=DATASET_CATEGORIES, default='', blank=True)
	source_url = models.URLField()

	def __unicode__(self):
		return self.title

class MetaExperiment(models.Model):

	slug = models.SlugField(max_length=50)
	title = models.CharField(max_length=50, default='')
	description = models.TextField()

	project = models.ForeignKey(Project, null=True)

	created_by = models.ForeignKey(Profile)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	metadata_category = models.ForeignKey('MetaCategory', null=True, blank=True)

	def fullname(self):
		return "{} | {}".format(self.project, self.title)

	def __unicode__(self):
		return self.title


class Experiment(models.Model):

	slug = models.SlugField(max_length=50)
	title = models.CharField(max_length=50, default='')
	description = models.TextField()

	#project = models.ForeignKey(Project, null=True)

	meta = models.ForeignKey('MetaExperiment', null=True, blank=True, related_name='experiments')

	created_by = models.ForeignKey(Profile)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	datasets = models.ManyToManyField(Dataset, through='ExperimentDatasets')
	timeperiods = models.ManyToManyField(TimePeriod, through='ExperimentTimePeriods')
	variables = models.ManyToManyField(Variable, through='ExperimentVariables')


	def fullname(self):
		return "{}".format(self.title)


	def __unicode__(self):
		return self.title


class ExperimentDatasets(models.Model):

	experiment = models.ForeignKey(Experiment)
	dataset = models.ForeignKey(Dataset)
	category = models.CharField(max_length=20, choices=EXPERIMENT_DATASET_CATEGORIES, default='', blank=True)

	def __unicode__(self):
		return "{} - {} ({})".format(self.experiment, self.dataset, self.category)


class ExperimentVariables(models.Model):

	experiment = models.ForeignKey(Experiment)
	variable = models.ForeignKey(Variable)
	category = models.CharField(max_length=20, choices=EXPERIMENT_VARIABLE_CATEGORIES, default='', blank=True)

	def __unicode__(self):
		return "{} - {} ({})".format(self.experiment, self.variable, self.category)


class ExperimentTimePeriods(models.Model):

	experiment = models.ForeignKey(Experiment)
	timeperiod = models.ForeignKey(TimePeriod)
	category = models.CharField(max_length=20, choices=TIMEPERIOD_CATEGORIES, default='', blank=True)

	def __unicode__(self):
		return "{} - {} ({})".format(self.experiment, self.timeperiod, self.category)


class MetaCategory(models.Model):

	slug = models.SlugField()
	description = models.TextField(default="")

	def __unicode__(self):
		return self.slug

class MetaTerm(models.Model):

	category = models.ForeignKey(MetaCategory)
	target = models.CharField(max_length=20, choices=META_TARGETS, default='', blank=True)
	order = models.IntegerField(default=0)
	name = models.SlugField()
	long_name = models.CharField(max_length=100, default="")
	help_text = models.TextField(default="", blank=True)
	multiple = models.BooleanField(default=False)
	freetext = models.BooleanField(default=False)
	#depends_on = models.ForeignKey('ModelMetaDependencies') 

	def __unicode__(self):
		return "{}|{}".format(self.category,self.name)

class MetaControlledValue(models.Model):

	term = models.ForeignKey(MetaTerm, related_name='values')
	value = models.CharField(max_length=100)

	def __unicode__(self):
		return "{}".format(self.value)

profiles/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Profile(models.Model):

	user = models.ForeignKey(settings.AUTH_USER_MODEL)

	institution = models.CharField(max_length=100, blank=True, null=True)
	city = models.CharField(max_length=100, blank=True, null=True)
	country = models.CharField(max_length=100, blank=True, null=True)

	complete = models.BooleanField(default=False)
	activated = models.BooleanField(default=False)

	def __unicode__(self):
		return '{}'.format(self.user.email)

	

submissions/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

from profiles.models import Profile
from experiments.models import Experiment, MetaTerm
from django.conf import settings

FILE_FORMATS = (('txt', 'Claris Text Format'), ('ziptxt', 'Zipped text format'), ('nc', 'netcdf'))
SUBMISSION_MODES = (('POST', 'HTTP POST'), ('PUT', 'FTP PUT'))
FREQUENCIES = (('day', 'daily data'), ('month', 'monthly data'))

filestorage = FileSystemStorage(settings.MEDIA_ROOT)

def make_upload_path(instance, filename):

	return "{}/{}/{}/uploaded/{}".format(instance.submission.owner.user, instance.submission.model.slug, instance.submission.experiment.slug, filename)


class Model(models.Model):

	slug = models.SlugField()
	title  = models.CharField(max_length=50, default="")
	contact = models.ForeignKey(Profile)
	description = models.TextField(default="", blank=True)

	def __unicode__(self):
		return self.title

class ModelMeta(models.Model):

	model = models.ForeignKey('Model', null=True, related_name='metadata')
	term = models.ForeignKey(MetaTerm)
	value = models.CharField(max_length=500, default="")

	def __unicode__(self):
		return "{}:{}".format(self.term, self.value)


class Submission(models.Model):

	owner = models.ForeignKey(Profile)			# Who owns this submission

	experiment = models.ForeignKey(Experiment, null=True)

	model = models.ForeignKey(Model)
	version = models.IntegerField(default=1)

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	notes = models.TextField(blank=True, default='')

	archive_path = models.CharField(max_length=500, default='', blank=True)
	archive_filename = models.CharField(max_length=500, default='', blank=True)

	def __unicode__(self):
		return "{} > {} ({}) version {}".format(self.experiment.meta, self.experiment, self.model, self.version)

class SubmissionMeta(models.Model):

	submission = models.ForeignKey('Submission', null=True, related_name='metadata')
	term = models.ForeignKey(MetaTerm)
	value = models.CharField(max_length=500, default="")

	def __unicode__(self):
		return "{}:{}".format(self.term, self.value)


class Upload(models.Model):

	timestamp = models.DateTimeField(auto_now_add=True)
	submission = models.ForeignKey(Submission, related_name='uploads')

	format = models.CharField(max_length=10, choices=FILE_FORMATS, default='txt')
	mode = models.CharField(max_length=10, choices=SUBMISSION_MODES, default='POST')

	path = models.CharField(max_length=500, default='', blank=True)
	filename = models.CharField(max_length=500, default='', blank=True)

	uploaded = models.FileField(null=True, storage=filestorage, upload_to=make_upload_path)

	status = models.CharField(max_length=200, blank=True, default='unknown')

	def __unicode__(self):
		return self.uploaded.url

profiles/forms.py
from django.forms import ModelForm
from profiles.models import Profile

class ProfileForm(ModelForm):

	class Meta:
		model = Profile
		fields = ['institution', 'city', 'country']

submissions/forms.py
from django.forms import ModelForm
from submissions.models import Model
from submissions.models import Submission
from submissions.models import Upload


class SubmissionModelForm(ModelForm):

	class Meta:
		model = Model
		exclude = []

class SubmissionForm(ModelForm):

	class Meta:
		model = Submission
		fields = ['experiment', 'model', 'notes', 'owner']

class UploadForm(ModelForm):

	class Meta:
		model = Upload
		fields = ['submission', 'format', 'uploaded']

experiments/views.py
from django.shortcuts import render
from rest_framework import viewsets
from experiments.models import TimePeriod, Dataset, MetaExperiment, Experiment
from experiments.serializers import TimePeriodSerializer, DatasetSerializer, MetaExperimentSerializer, ExperimentSerializer


# Create your views here.
class TimePeriodViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows timeperiods to be viewed or edited
    """
    queryset = TimePeriod.objects.all()
    serializer_class = TimePeriodSerializer


class DatasetViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows datasets to be viewed or edited.
    """
    queryset = Dataset.objects.all()
    serializer_class = DatasetSerializer


class MetaExperimentViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows meta experiments to be viewed or edited.
    """
    queryset = MetaExperiment.objects.all()
    serializer_class = MetaExperimentSerializer


class ExperimentViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows experiments to be viewed or edited.
    """
    queryset = Experiment.objects.all()
    serializer_class = ExperimentSerializer

profiles/views.py
from django.shortcuts import render

# Create your views here.

submissions/views.py
import os

from django.shortcuts import render
from rest_framework import viewsets
from rest_framework import views
from rest_framework import parsers
from rest_framework import mixins
from submissions.serializers import ModelSerializer, ModelMetaSerializer
from submissions.serializers import SubmissionSerializer, UploadSerializer
from submissions.models import Model, ModelMeta, Submission, Upload
from profiles.models import Profile

from rest_framework import permissions
from submissions.permissions import UploadsIsOwnerOrReadOnly

class ModelViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows models to be viewed or edited
    """
    queryset = Model.objects.all()
    serializer_class = ModelSerializer
    permission_classes = [permissions.IsAuthenticated]


class ModelMetaViewSet(viewsets.ModelViewSet):

    queryset = ModelMeta.objects.all()
    serializer_class = ModelMetaSerializer
    permission_classes = [permissions.IsAuthenticated]
        

class SubmissionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows submissions to be viewed or edited
    """
    permission_classes = [permissions.IsAuthenticated]
    queryset = Submission.objects.all()
    serializer_class = SubmissionSerializer

    def get_queryset(self):
        try:
            user_profile = Profile.objects.get(user=self.request.user)
        except:
            return None

        return Submission.objects.filter(owner=user_profile)

#class UploadViewSet(viewsets.ModelViewSet):
#    """
#    API endpoint that allows upload to be viewed or edited
#    """
#    permission_classes = [IsOwnerOrReadOnly]
#    queryset = Upload.objects.all()
#    serializer_class = UploadSerializer

class UploadView(viewsets.ModelViewSet):

    permission_classes = [UploadsIsOwnerOrReadOnly]
    queryset = Upload.objects.all()
    serializer_class = UploadSerializer
    parser_classes = (parsers.FormParser, parsers.MultiPartParser)

#    def post(self, request, filename):

#        upload_file = request.data['file']

#        with open('test', 'w') as target:
#            for chunk in upload_file.chunks():
#                target.write(chunk)

    def perform_destroy(self, instance):

        # Delete the actual file
        if instance.uploaded:
            if os.path.isfile(instance.uploaded.path):
                os.remove(instance.uploaded.path)

        # Delete the database
        instance.delete()

web/templates/web/admin_submissions.html
{% extends "web/base.html" %}

{% block title %}CORDEX Experiment Manager | Experiments {% endblock %}

{% block content %}



    <div class="row">
      <h4>Experiment submissions matrix</h4>
      <table class="table table-bordered table-condensed">
      
          <tr><td></td>
            {% for model in models %}<td>{{ model }}</td>{% endfor %}
          </tr>

      {% for name, meta_experiment in matrix.items %}
          <tr><td><strong>{{ name }}</strong></td></tr>

          {% for name, experiment in meta_experiment.items %}
            <tr><td>{{ name }}</td>

               {% for column in experiment %}
                  
                  {% if column > 0 %}
                    <td style="background-color:green">{{ column }}</td>
                  {% else %}
                    <td></td>
                  {% endif %}

               {% endfor %}
            </tr>
          {% endfor %}

      {% endfor %}

      </table>


    </div>



{% endblock %}

web/templates/web/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" ng-app="cordexManager">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CORDEX Experiment Manager{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'web/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/manager.css' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="{% static 'web/js/angular.min.js' %}"></script>
    <script src="{% static 'web/js/jquery.min.js' %}"></script>
    <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'web/js/controllers.js' %}"></script>

    <script src="{% static 'web/js/speakingurl.min.js' %}"></script>
    <script src="{% static 'web/js/slugify.min.js' %}"></script>


  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Experiment Manager</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'web-experiments' 'cordex-esd' %}">Experiments</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'web-user-submissions' %}">Submissions</a></li>
            <li><a href="{% url 'web-models-list' %}">Models</a></li>
            {% endif %}

            {% if user.is_staff %}
            <li><a href="{% url 'web-admin-submissions' %}">All Submissions</a></li>
            {% endif %}

          </ul>
          <ul class="nav navbar-nav navbar-right">

            {% if user.is_authenticated %}
              <p class="navbar-text">Logged in as </p>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user.first_name }} {{ user.last_name }}<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                      <li><a href="{% url 'web-profile' %}">View Profile</a></li>                    
                      <li><a href="{% url 'web-logout' %}">Logout</a></li>
                  </ul>
              </li>

            {% else %}
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                      <li><a href="{% url 'web-login' %}">about logging in</a></li>                    
                      <li><a href="{% url 'social:begin' 'linkedin-oauth2' %}?next={% url 'web-profile' %}">via LinkedIn</a></li>
                      <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={% url 'web-profile' %}">via Google</a></li>
                  </ul>
              </li>

          </ul>
        </li>
            {% endif %}
          </ul>
        </div><!--/.navbar-collapse -->
      
      </div>
    </nav>

    <div class="container">

      <div class="row">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}
      </div>

      {% block content %}{% endblock %}
    </div>
<script>


</script>
  </body>
</html>

web/templates/web/experiment_detail.html
{% extends "web/base.html" %}

{% block title %}CORDEX Experiment Manager | Experiments {% endblock %}

{% block content %}


    <div class="row">
      <h3><a href="{% url 'web-experiments' project.slug %}">{{ project.title }}</a></h3>
      <h4>{{ meta_experiment.title }} > {{ experiment.title }}</h4><hr/>
      <div>
        <p>{{ experiment.description }}</p>
        <p><a class="btn btn-primary btn-sm" href="{% url 'web-experiment-submissions' project.slug meta_experiment.slug experiment.slug %}">Create a new submission for this experiment</a> You currently have <strong>{{ user_submissions|length }}</strong> submissions for this experiment tier</p>
      </div>
    </div>
     
    <div class="row">

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Experiment Datasets</div>
            <div class="panel-body">
              {% for dataset in datasets %}
                  <strong>{{ dataset.category }}</strong> | {{ dataset.dataset.title }} ({{ dataset.dataset.category }})
                  <p>{{ dataset.dataset.description }}</p>
                  <p>Data source URL: <a href="{{ dataset.dataset.source_url }}">{{ dataset.dataset.source_url }}</a></p>
              {% endfor %}
            </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Experiment Time Periods</div>
            <div class="panel-body">
              {% for timeperiod in timeperiods %}
                  <p><strong>{{ timeperiod.category }}</strong> | {{ timeperiod.timeperiod.begin | date:'d M Y'}} to {{ timeperiod.timeperiod.end | date:'d M Y' }}</p>
              {% endfor %}
            </div>
      </div>
    </div>

    </div> <!-- /container -->

{% endblock %}

web/templates/web/experiments.html
{% extends "web/base.html" %}

{% block title %}CORDEX Experiment Manager | Experiments {% endblock %}

{% block content %}

    <div class="row">
    <h3>{{ project.title }}</h3>
    {{ project.description }}
    <p>
    <a href="{{ project.url }}">Read more at : {{ project.url }}</a>
    </p>
    </div>

    <div class="row">
      <h4>There are currently <strong>{{ meta_experiments|length }}</strong> experiments published under this project:</h4>
    </div>

    <hr/>

    <div class="row">
    {% for meta_experiment in meta_experiments %}
          <div class="panel panel-default">
            <div class="panel-heading">{{ meta_experiment.fullname }}</div>
            <div class="panel-body">{{ meta_experiment.description }}<hr/>
                <p>There are <strong>{{ meta_experiment.experiments.all | length }}</strong> subsidary experiments within this experiment</p>
                
                {% for experiment in meta_experiment.experiments.all %}                
                  <div class="panel panel-default">
                    <div class="panel-heading">{{ experiment.fullname }} id# = {{ experiment.id }} </div>
                    <div class="panel-body">{{ experiment.description }}<hr/>
                    <a class="btn btn-primary btn-sm" href="{% url 'web-experiment-detail' project.slug meta_experiment.slug experiment.slug  %}">More details and/or submit results to this experiment</a>
                    </div>
                  </div>
                {% endfor %}
           
            </div>
          </div>
      {% endfor %}
    </div> <!-- /container -->

{% endblock %}

web/templates/web/submissions.html
{% extends "web/base.html" %}

{% block title %}CORDEX Experiment Manager | Experiments {% endblock %}

{% block content %}

    <div class="row">
      <h3><a href="{% url 'web-experiments' project.slug %}">{{ project.title }}</a></h3>
      <h4>{{ meta_experiment.title }} > {{ experiment.title }}</h4><hr/>
    </div>

    <div class="row">
      <h4>You currently have <strong>{{ user_submissions|length }}</strong> submissions active for this experiment ({{ meta_experiment }} > {{ experiment }})</h4>
      <a class="btn btn-warning" href="#add_submission">Add a new submission</a>
      <hr/>
    </div>

    <div class="row">
      {% for submission in user_submissions %}
        <div class="panel panel-default">
          <div class="panel-heading">{{ submission }} #{{ submission.id }}</div>
          <div class="panel-body">
              <p>Created: {{ submission.created | date:'H:m D M Y' }} ( last modified: {{ submission.modified | date:'H:m D M Y' }} )</p>
              {% if submission.notes %}
                <p>Notes: {{ submission.notes }} </p>
              {% endif %}            
              <hr/>
              
              <p>
                {% if submission.uploads.all.count == 0 %}
                You have not uploaded any files to this submission
                {% else %}
                You have uploaded <strong>{{ submission.uploads.all | length }}</strong> files to this submission
                {% endif %}
              </p>
              <table class="table table-striped table-condensed">
                <tr>
                  <td><strong>File</strong></td>
                  <td><strong>Format</strong></td>
                  <td><strong>Timestamp</strong></td>
                  <td><strong>Status</strong></td>
                  <td><strong>Actions</strong></td>
                </tr>
              {% for upload in submission.uploads.all %}
                <tr>
                  <td>{{ upload.uploaded.url }}</td>
                  <td>{{ upload.format }}</td>
                  <td>{{ upload.timestamp | date:'H:m D M Y' }}</td>
                  <td>{{ upload.status }}</td>
                  <td><a class="upload-delete" href="{% url 'api:upload-detail' upload.id %}"><span data-toggle="tooltip" data-placement="bottom" title="Delete this upload" class="glyphicon glyphicon-remove-circle"></span></a></td>
                </tr>
              {% endfor %}
              </table>

              <form class="upload-form" action="{% url 'api:upload-list' %}" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <input type="hidden" name="submission" value="{{ submission.id }}">

                  <div class="form-group">
                      <label for="{{ upload_form.uploaded.id_for_label }}">Select a file to upload</label>
                        {{ upload_form.uploaded }}
                  </div>
                  <div class="form-group">
                      <label for="{{ upload_form.format.id_for_label }}">Select the data format of the uploaded file</label>
                       {{ upload_form.format }}
                  </div>
                  <input type="submit" value="upload">
              </form>
          </div>
        </div>
      {% endfor %}
    </div>


    <div class="row">
          <a id="add_submission"></a>
          <div class="panel panel-warning">
            <div class="panel-heading">Create a new submission</div>
            <div class="panel-body">
              <form method="post" action="{% url 'web-experiment-submissions' project.slug meta_experiment.slug experiment.slug %}">
              {% csrf_token %}
                <p>Your submission will be under the {{ project }} project and for experiment {{ meta_experiment }} > {{ experiment }}</p>

                <input type="hidden" name="project" value="{{ project.id }}">
                <input type="hidden" name="experiment" value="{{ experiment.id }}">
                <input type="hidden" name="owner" value="{{ user_profile.id }}">


                <div class="form-group">
                  <label for="{{ form.model.id_for_label }}">Select which of your saved models was used for this submission</label>
                  {{ form.model }}{{ form.model.errors }} <a href="{% url 'web-profile' %}">Add models to your profile</a>

                </div>

                <div class="form-group">
                  <label for="id_notes">Notes</label>
                  <textarea id="id_notes" name="notes" class="form-control" placeholder="Enter any relevant notes to yourself or others"></textarea>
                </div>
                <input type="submit" class="form-control btn btn-primary" value="Create new submission">
              </form>

            </div>
          </div>
    </div>




    <script>

      $(document).ready(function() {

          $(function () {
              $('[data-toggle="tooltip"]').tooltip()
          });

          $(".upload-form").submit(function(e) {
              
              var formdata = new FormData(e.target);
              console.log('submitting');
              var url = $(e.target).attr('action');
              console.log('url = ' + url);
              
              $.ajax({
                  url: url,
                  type: 'POST',
                  data: formdata,
                  contentType: false,
                  processData: false,
                  success: function(res) { 
                    console.log('success!');
                    location.reload();
                  },

              });

              return false;
          });

          $(".upload-delete > span").click(function(e) {
              alert('deleting');
              var formdata = new FormData();
              console.log("delete!");
              var url = $(e.target).parent().attr('href');
              console.log(url);
              
              formdata.append('csrfmiddlewaretoken', '{{ csrf_token }}');
              formdata.append('_method', 'DELETE');

              $.ajax({
                  url: url,
                  data: formdata,
                  contentType: false,
                  processData: false,
                  type: 'POST',
                  success: function(res) { 
                    console.log('response: ' + res);
                    location.reload();
                  }
              });

              return false;    
          });

      });
    </script>

{% endblock %}